#2015
pytest -s -v -l --testdata="{'spreadsheetId': '1iM99sD2ylm3Ny3Pksoz3lFcp1jgUucY9KW-BsYfBTjs', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1DoQc3yC3YY9i2OP-hFtjVU_SsmdJzU-cpc9DOvuFZ5s', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1_UXVmTwveJnU35YtjOFZPExGNQGcZ0YGRHfJkqmuAQ0', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1H6kohzf8O5hd5sJVpGLMPf71UU1z3j6cnaeJN1qk_OQ', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1i1DmgmJOoikIhQ4YdXg_cuMKSvEe1Av-RsbIdSHFnyo', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1EOLMZ3nTE_Q_V7bfqZvbS4Udw_d5s0QAQ8k9KIivPVU', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1FuQlkEb09cBXoTKRmCkKu89hkSOxTz4NA79zyr41j4o', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1fI9V56aVMVM9uY1Jggvt-pv2CoqZHFeM0W__Oy78p4E', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1GYdPvKvH_gmbi_GKIglBkLlpomNUULTgEK43RJ1W_qo', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1plp3eDm6wE_m9JqZqmHO2pADf4XirKgAbB2efRkrEO4', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1Wi0Oo6QelmPvdiaefoiSLeTARzloH__yM694iHHBwYo', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1gkmRkkGwNmmerWb-tAci5ah26oI9mjc5AwqGq_e-wFs', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1LH9lQGHgONiDb-IrJK7TY8EqAVvHskPHeB655O53ghU', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1hOZUeCn8BjbUhapsZNU5fhVt6DnpJbrAFEwDjIBd7e8', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1d0BcSQJ-5QHtKmVzhheKt1KBAAcxGPKco5yJ0AOXAw4', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1SWcgq6wBLPkpOz-1-sHkO0_fQM1W0QlwqfVJXW7YFzY', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1WG0c_nKSFTqVUOOpb-X1Jmv_MOs_E4_Iu6S_vBexSaA', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2015_lineup.csv', 'pairing': False}" -m lineup_analysis