#2016
pytest -s -v -l --testdata="{'spreadsheetId': '18qnMqE1QX8sTLxLSUw6AVulhBqE5v_3sDn1BRipRJ80', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '15ct4Hfn235xforQAB5GJh4EmfB1kCop6cLYbtmhJLOA', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '19fXX9z03z3tCGkh0TAIAfeKy47NsfUjkRvGbQcBZtbM', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1ubVojcFz19wbvWFpW40x0lRNW45uQNqPaxmA9S4v6ZU', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1sreIkvzmnB8TJJg690vkNflXXUGuR7hRIwx_6UGx9a8', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1C4e4DuVAV0Df94--UeIAOzp-6UXQrjr6ptnYlZFZ3Fw', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1Tk2HXBS-Ad4nKyBkNL5jp8LhSV0JuJ8TPeds9pcoZQ0', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1IdgzfmIhYKvygz0qNsOkchCabloAHgMX3BunB2A6reI', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1UpDZpiyzRW7pjc6YEe2i8N6wkeAO61qZocHOAzdqmwI', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1aidHjvsbXiXWALhn9VxC5o54D9ZfBA3KbB8JTtPy7-M', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1YLZpLo8Vo99VdcFymk5z0G2A6gD76zOL6syxtn8VRUU', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1FdfpHXacpUWkcNHIQpSZCEc1FNrGyDErMJNGZqLeLoQ', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1KTVy5LDvjJXGcZHivWgPtROe1po-LwmO5NyBmmyNfAQ', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1GKYzPg0X6vT_LGvWHjBDYz3hyxNZN8L0wu2KzyXO15w', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1UpDZpiyzRW7pjc6YEe2i8N6wkeAO61qZocHOAzdqmwI', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1SWcgq6wBLPkpOz-1-sHkO0_fQM1W0QlwqfVJXW7YFzY', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis
pytest -s -v -l --testdata="{'spreadsheetId': '1WG0c_nKSFTqVUOOpb-X1Jmv_MOs_E4_Iu6S_vBexSaA', 'rangeName': 'A1:L1447', 'QB_std': 0, 'RB_std': 0, 'WR_std': 0, 'TE_std': 0, 'DST_std': 0, 'FLX_std': 0, 'count': 0, 'min_sal': 58000, 'master_csv': '2016_lineup.csv', 'pairing': False}" -m lineup_analysis