# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pwd
            ls
            flake8 --exclude=venv* --statistics --max-line-length=180
            # Workaround to ignore pyautogui in CI testing.
            sudo rm -r /home/circleci/project/venv/lib/python3.7/site-packages/pyautogui
            sed -i s/"import pyautogui"/"# import pyautogui"/ /home/circleci/project/venv/lib/python3.7/site-packages/flex/lib/sheets/prerequisite.py
            sed -i s/"import pyautogui"/"# import pyautogui"/ /home/circleci/project/flex/tests/tier-0/testscrape/test_scrape_ffa.py
            sed -i s/"import pyautogui"/"# import pyautogui"/ /home/circleci/project/flex/tests/tier-2/test_update/test_create_post_Gsheet.py
            cd /home/circleci/project/flex && pytest -s -v -l --testdata="{'spreadsheetId': '1a5WqcJrI6_FPbsWdXeoXWi-kOgrjjhrqDgOdScl2t90', 'rangeName': 'A1:L1447'}" -m regression 

