# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # Show us where we are
            pwd
            # Tell us what we have
            ls
            # Test python code according to the flake8 standard.
            flake8 --exclude=venv* --statistics --max-line-length=180
            # Execute workflow gating tests
            cd /home/circleci/project/flex && pytest -s -v -l --junit-xml /tmp/test_results.xml --testdata="{'spreadsheetId': '1a5WqcJrI6_FPbsWdXeoXWi-kOgrjjhrqDgOdScl2t90', 'rangeName': 'A1:L1447'}" -m regression

      - store_test_results:
          path: /tmp

      - store_artifacts:
          path: /tmp/test_results.xml

